---
- name: Deploy ABCtechnologies app to kubernetes cluster
  hosts: localhost
  tasks:
    - name: Create deployment
      shell: "kubectl apply -f deployment.yml"

    - name: Create service
      shell: "kubectl apply -f service.yml"
